# Online HMAB config for docker-compose runtime
database:
  dbname: "pgdb"
  user: "pguser"
  password: "123456"
  host: "postgres"
  port: 5432

system:
  enable_tune: true
  with_mv: false
  mv: "MV"
  max_memory: 25000
  hyp_file: "./hyp_files/temp.txt"

tuning:
  hyp_check_rounds: 1
  rounds: 1
  super_static_context_size: 2
  cluster_id_start: 1
  queries_start: 0
  batch_size: 10
  offset: 1

logging:
  log_file: "online_mab.log"
  log_level: "INFO"

tables:
  small_table_ignore_threshold: 0

bandit:
  input_alpha: 0.05
  input_lambda: 0.5

query:
  schema: null
